name: Merge staging to main every 2 minutes

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Merge staging -> main
        run: |
          git checkout main
          git merge staging -m "Merge staging into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
