name: Daily - Merge staging into main

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Merge staging -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge staging into main
          github_token: ${{ secrets.ACCESS_TOKEN }}
