name:= Merge Manual

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge branch `auto-update` into main
      run: |
        git config user.name Rahul Deshar
        git config user.email desarrahul@gmail.com
        git checkout main
        git merge --squash auto-update
        git commit -m "Manual merge - $(date +'%Y-%m-%d')" # Set commit message with current date
        git push --quiet --set-upstream origin main
      env:
        PAT: ${{ secrets.ACCESS_TOKEN }}
