name: Push Merge - test

on:
  push:
    branches:
      - auto-update

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge branch `auto-update` into main
        run: |
          git config user.name Rahul Deshar
          git config user.email desarrahul@gmail.com
          pwd
          git config --list
          git branch
          git fetch
          git branch
          git checkout main
          git merge --squash auto-update --allow-unrelated-histories
          git commit -m "Merge Test - $(date +'%Y-%m-%d')" # Set commit message with current date
          git push --quiet --set-upstream origin main
        env:
          PAT: ${{ secrets.ACCESS_TOKEN }}
