name: Merge with Test Branch

on:
  push:
    branches:
      - auto-update

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Merge Commits
        run: |
          git status
          git checkout main
          git merge --no-ff --no-commit test
          git commit -m "Merge with auto-update branch"
          git push origin main
